version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "noties"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-waqtfqln21f7"
s3_prefix = "noties"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
