AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  noties

  Sample SAM Template for noties

Parameters:
  DomainName:
    Type: String
    Description: The domain name we are using in the environment
    Default: nickswiss.io

Globals:
  Function:
    Timeout: 3

Resources:
  SubdomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub 'noties.${DomainName}'

  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/email_worker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          AUTH_DB: !Ref AuthDb
          GMAIL_OAUTH_SECRET: 'noties/gmail_oauth'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthDb
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:noties/*"
      Events:
        EmailCheckSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(10 minutes)'
            Name: !Sub "${EmailFunction}-MailCheckSchedule"
            Description: Runs every 10 minutes
            Enabled: true
      Layers:
        - !Ref ProjectSharedLibs

  EmailFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${EmailFunction}"
      RetentionInDays: 7

  ###### OAuth Apis #######

  OAuthCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'noties.${DomainName}'
      SubjectAlternativeNames:
        - !Sub '*.noties.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:  # TODO: Investigate here <--
        - DomainName: !Sub 'noties.${DomainName}'
          HostedZoneId: !Ref SubdomainHostedZone

  OAuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        UsagePlan:
          CreateUsagePlan: SHARED
          UsagePlanName: !Sub '${AWS::StackName}-api-usage-plan'
      Domain:
        CertificateArn: !Ref OAuthCertificate
        Route53:
          HostedZoneId: !Ref SubdomainHostedZone
        DomainName: !Sub 'oauth.noties.${DomainName}'
        EndpointConfiguration: EDGE
        SecurityPolicy: TLS_1_2

  OAuthForm:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/oauth_form/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          GMAIL_OAUTH_SECRET: 'noties/gmail_oauth'
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:noties/*"
      Layers:
        - !Ref ProjectSharedLibs
      Events:
        AddSiteApi:
          Type: Api
          Properties:
            Path: /form
            Method: get
            RestApiId: !Ref OAuthApi

  OAuthSubmit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/oauth_submit/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DOMAIN_NAME: !Sub 'oauth.noties.${DomainName}'
          GMAIL_OAUTH_SECRET: 'noties/gmail_oauth'
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:noties/*"
      Layers:
        - !Ref ProjectSharedLibs
      Events:
        AddSiteApi:
          Type: Api
          Properties:
            Path: /submit
            Method: post
            RestApiId: !Ref OAuthApi

  OAuthCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/oauth_callback/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          OAUTHLIB_RELAX_TOKEN_SCOPE: 1
          DOMAIN_NAME: !Sub 'oauth.noties.${DomainName}'
          GMAIL_OAUTH_SECRET: 'noties/gmail_oauth'
          AUTH_DB: !Ref AuthDb
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthDb
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:noties/*"
      Layers:
        - !Ref ProjectSharedLibs
      Events:
        AddSiteApi:
          Type: Api
          Properties:
            Path: /callback
            Method: get
            RestApiId: !Ref OAuthApi

  AuthDb:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub '${AWS::StackName}-authdb'
      PrimaryKey:
        Name: email
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  #######################################
  # Lambda Layers (Shared Libraries)
  #######################################
  ProjectSharedLibs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/shared/libs/
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

#Outputs:
#  HelloEfsApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello EFS function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
